### ISSUE TITLE
Dependencies missing in aur devscripts

### ISSUE THREAD

**Issue by weilinfox** [ItachiSan/linux_packaging#10]
It seems that ``perl-moo`` , ``perl-ipc-run`` and ``perl-lwp-protocol-https`` are also required for ``uscan``.

**Comment by ItachiSan** [comment]
Ok! That's great to hear :smile: 
I was hoping that `namcap` would provide better recommendations, but seems not.
I will check the package as soon as possible and add those as `optdepends` in case :wink:

**Comment by ItachiSan** [comment]
With the latest devscripts release, the issue is solved, as I added all the related `optdepends`. :)
