### ISSUE TITLE
devscripts: conflict with community/checkbashisms

### ISSUE THREAD

**Issue by xiota** [ItachiSan/linux_packaging#11]
The `devscripts` package conflicts with `checkbashisms`.  Here is relevant output from `pacman -S checkbashisms`:
````
checkbashisms: /usr/bin/checkbashisms exists in filesystem (owned by devscripts)
checkbashisms: /usr/share/bash-completion/completions/checkbashisms exists in filesystem (owned by devscripts)
````

In addition to the conflicting files, `checkbashisms` provides the man page, which is not included with `devscripts`.
````
checkbashisms usr/bin/checkbashisms
checkbashisms usr/share/bash-completion/completions/checkbashisms
checkbashisms usr/share/man/man1/checkbashisms.1.gz
````

Possible solutions:
1. Remove conflicting files from `devscripts`.  Add `checkbashisms` as a dependency or optional dependency.
2. Add `checkbashisms` to the provides/conflicts lists of `devscripts`.

**Comment by ItachiSan** [comment]
Sorry for the delay, just noticed the request.

I've added the scripts man pages to the package and the conflict & provides definitions. :smile:
