### ISSUE TITLE
error with devscripts

### ISSUE THREAD

**Issue by professorjamesmoriarty** [ItachiSan/linux_packaging#3]
Trying to install devscripts gives me a error:

```
warning: failed to load external entity "/usr/share/xml/docbook/xsl-stylesheets-1.79.1/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/xsl-stylesheets-1.79.1/manpages/docbook.xsl
make[1]: *** [Makefile:65: deb-reversion.1] Error 4

```

**Comment by professorjamesmoriarty** [comment]
As a temp solution I've added a symlink from `/usr/share/xml/docbook/xsl-stylesheets-1.79.2/` to `/usr/share/xml/docbook/xsl-stylesheets-1.79.1/`. Looks to need some sed magic.

**Comment by ItachiSan** [comment]
@shaggytwodope just updated both the package and the patch.
