### ISSUE TITLE
Arch Linux devscripts package missing "perl-pod-parser" dependency

### ISSUE THREAD

**Issue by CodingKoopa** [ItachiSan/linux_packaging#6]
Thank you for the useful packages! The Arch Linux `devscripts` package failed to build for me, like so:
```
po4a --previous --no-backups --keep=0 devscripts-po4a.conf
Unknown format type: pod.
```
Installing the [`perl-pod-parser`](https://www.archlinux.org/packages/community/any/perl-pod-parser/) package seems to have fixed this issue. Also see relevant FreeBSD bug relating to this [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248541).

**Comment by ItachiSan** [comment]
Hey, thanks for the issue report!

I've confirmed the issue, took a bit to set up the missing stuff on the new machine.

Adding the dependency as a `makedepends` does the trick.

The update will come soon, as soon as I have set up all the proper `aur-out-of-date` rules :smile:

**Comment by wget** [comment]
Building the package on a clean Arch Linux environment is working, so I assume we can close this one too, @ItachiSan :)

**Comment by ItachiSan** [comment]
I guess I can :smile:
