### ISSUE TITLE
Arch Linux devscripts is missing dpkg-vendor

### ISSUE THREAD

**Issue by wget** [ItachiSan/linux_packaging#7]
Hi there,

As I was trying to update my Arch , I noticed your package devscripts wasn't building any more due to this error:
```
==> Starting build()...
rm -f version
dpkg-parsechangelog -SVersion > version
make -C scripts/
make[1]: Entering directory '/home/wget/.cache/yay/devscripts/src/devscripts/scripts'
dpkg-vendor: error: vendor default doesn't exist in /etc/dpkg/origins
sed -e "s/###VERSION###/2.19.7/" bts.pl  > bts.tmp
```

I think this is due to dpkg-vendor missing. Would you mind packaging this dependency?

**Comment by ItachiSan** [comment]
Sure, I will publish a version soon.
As I don't use this software anymore, can you tell me if it is a build-only dependency or if it is used also from the scripts? Thanks :smile:

**Comment by ItachiSan** [comment]
Hey, I double-checked and I don't have your issue; in my case, `dpkg-vendor` relies inside `dpkg`.
Which version are you using? :smiley:

**Comment by wget** [comment]
@ItachiSan Here you are:

```
(master)[wget@hermes devscripts]$ dpkg-vendor --version
Debian dpkg-vendor version 1.20.5.

This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
```

To answer your question, since I am a user of `yay`, I had to install manually your dependencies (unfortunately `yay` [doesn't support building local repo](https://github.com/Jguer/yay/issues/694)).

For the future, (if not done already) it may be wise to check out whether it upgrades with `yay`, this is what I do for my Arch Linux packages as this pacman/aur wrapper is widely used nowadays =) Have used `devscripts` for ages with `yay`, it is the first time I encounter this issue :)

Please let me know if you need further help to debug this issue =)

**Comment by ItachiSan** [comment]
@wget yes, I do need further info; I noticed I got a `dpkg` package from AUR but it is *1.19.7*.
Which version of it did you install? Where did you fetch the `PKGBUILD`?

**Comment by wget** [comment]
@ItachiSan The `dpkg`package I have installed on my system is the one you have in the `community` repo.

```
[wget@hermes ~]$ yay -Si dpkg
Repository      : community
Name            : dpkg
Version         : 1.20.5-2
Description     : The Debian Package Manager tools
Architecture    : x86_64
URL             : https://tracker.debian.org/pkg/dpkg
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : xz  zlib  bzip2  perl
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 1795.83 KiB
Installed Size  : 8455.17 KiB
Packager        : Anatol Pomozov <anatol.pomozov@gmail.com>
Build Date      : Tue 13 Oct 2020 18:25:35 CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

So indeed the version I have is 1.20.5-2 and not 1.19.7 ;)

**Comment by ItachiSan** [comment]
Hi, sorry for the long wait (life happened :smile:)
I tried to build the package and had no issue; I will push the update up and I would like you to verify stuff works for you :smiley:

**Comment by wget** [comment]
@ItachiSan Yeah \o/ I finally have been able to update this package on my Arch Linux \o/ Seems like what you have performed as changes did the trick :)

**Comment by ItachiSan** [comment]
Glad to hear that~ :smiley:
