### ISSUE TITLE
Devscripts: missing perl dependencies for uscan

### ISSUE THREAD

**Issue by selmf** [ItachiSan/linux_packaging#9]
The uscan tool supplied by devscripts needs the following perl modules to work:

- perl-file-dirlist (currently *not* available as package or AUR on Arch Linux)
- perl-file-touch

It probably would be a good idea to add these to the dependencies or optional dependencies of devscripts. Perl packaging is new to me, but I have made a rudimentary package for perl-file-dirlist which I could improve for AUR publication if you are interested.

**Comment by ItachiSan** [comment]
Hi, thanks for the suggestion! I believe that it is best to have them as `optdepends` 😄 
I will see for some Perl PKGBUILD later today, hopefully with a good result!

**Comment by ItachiSan** [comment]
Marking this as done as verification is discussed in #8 , so comments for this can be added there too.
